stages:
  - build
  - test
  - archive
  - deploy

build_project:
  stage: build
  script:
    - xcodebuild clean -project RxMVVM.xcodeproj -scheme SchemeName | xcpretty
    - xcodebuild test -project RxMVVM.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' | xcpretty -s
  tags:
    - ios_11-3
    - xcode_9-3
    - macos_10-13

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/RxMVVM -scheme SchemeName
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/RxMVVM.xcarchive" -exportPath "build/RxMVVM.ipa" -exportProvisioningProfile "ProvisioningProfileName"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/RxMVVM.ipa
  tags:
    - ios_11-3
    - xcode_9-3
    - macos_10-13
