stages:
  - build
  - test
  - release
  - deploy
  
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - pod install
  - sudo gem install bundler
  - bundle install
 
build_project:
  stage: build
  script:
    - xcodebuild clean -workspace "RxMVVM.xcworkspace" -scheme "RxMVVM" | xcpretty
    - xcodebuild test -workspace "RxMVVM.xcworkspace" -scheme "RxMVVM" -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' | xcpretty -s
    - xcodebuild clean archive -archivePath build/MyApp \
                         -scheme MyApp
    - xcodebuild -exportArchive \
           -exportFormat ipa \
           -archivePath "build/RxMVVM.xcarchive" \
           -exportPath "build/RxMVVM.ipa" \
           -exportProvisioningProfile "Rust_Adhoc"
  tags:
    - master

release:
  stage: release
  script:
  - bundle exec fastlane release
  artifacts:
    paths:
      - build/RxMVVM.ipa
  tags:
    - stable
  only:
     - /^release-.*$/
     - develop
