stages:
  - build
  - test
  - release
  - deploy
  
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  YOUR_PERSONAL_TOKEN: "sCYyAFR8y4x7oyKDzmWy"
  GIT_CI_PASS: "hoanguit_99"
  GIT_CI_USER: "Nguyen_Hoang99"
  CI_PROJECT_PATH: "Nguyen_Hoang99/RxMVVM"

before_script:
    - git remote set-url origin https://$GIT_CI_USER:$GIT_CI_PASS@gitlab.com/$CI_PROJECT_PATH.git
    - git config --global user.name "Nguyen_Hoang99"
    - git config --global user.email "hoanguit@gmail.com"

build_project:
  stage: build
  script:
    - sudo gem install bundler
    - bundle install
    - bundle exec fastlane build
  tags:
    - master
  only:
    - triggers
    - schedules
    - develop
    
release:
  stage: release
  script:
  - bundle exec fastlane release
  artifacts:
    paths:
      - build/RxMVVM.ipa
  tags:
    - stable
  only:
     - triggers
     - schedules
     - develop
deploy:
  stage: deploy
  script:
  - bundle exec fastlane deploy
  tags:
    - master
  only:
    - triggers
    - schedules
    - develop
