stages:
  - build
  - test
  - release
  - deploy
  
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
    - git config --global user.name "Nguyen_Hoang99"
    - git config --global user.email "hoanguit@gmail.com"

build_project:
  stage: build
  script:
    - bundle exec fastlane test
  tags:
    - master

# build_project:
#   stage: build
#   script:
#     - sudo gem install bundler
#     - bundle install
#     - bundle exec fastlane build
#   tags:
#     - master

# release:
#   stage: release
#   script:
#   - bundle exec fastlane release
#   artifacts:
#     paths:
#       - build/RxMVVM.ipa
#   tags:
#     - stable
#   only:
#      - /^release-.*$/
#      - develop
# deploy:
#   stage: deploy
#   script:
#   - bundle exec fastlane deploy
#   tags:
#     - master
