stages:
  - build
  - test
  - release
  - deploy

before_script:
  - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace "RxMVVM.xcworkspace" -scheme "RxMVVM" | xcpretty
    - xcodebuild test -workspace "RxMVVM.xcworkspace" -scheme "RxMVVM" -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' | xcpretty -s

  tags:
    - master

release:
  stage: release
  script:
  - fastlane release
  artifacts:
    paths:
      - build/RxMVVM.ipa
  tags:
    - stable
  only:
     - /^release-.*$/
     - master
