# default_platform(:ios)
#
# platform :ios do
#
#
# end
# lane :beta do
#   build_app(
#     export_method: "app-store",
#     export_options: {
#       provisioningProfiles: {
#         "com.example.bundleid" => "Provisioning Profile Name",
#         "com.example.bundleid2" => "Provisioning Profile Name 2"
#       }
#     }
#   )
# end

lane :release do
  # Ensure that your git status is not dirty
  ensure_git_status_clean
  # Increment the build number (not the version number)
  # Providing the xcodeproj is optional
  increment_build_number(xcodeproj: "RxMVVM.xcodeproj")
  # Commit the version bump
  commit_version_bump(xcodeproj: "RxMVVM.xcodeproj")
  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name
  add_git_tag
  # Push the new commit and tag back to your git remote
  push_to_git_remote
end


lane :release do
  sync_code_signing
  enable_automatic_code_signing(path: "RxMVVM.xcodeproj")
  build_app(scheme: "RxMVVM")
  hockey(api_token: "[9de01f054ce092ef372fa63bc7aab84f9f0588e4]")
end
