default_platform(:ios)

platform :ios do
desc "Test distribution "

 # ------------ Build project -------------
lane :build do
clean_cocoapods_cache
# clear_derived_data
xcclean(workspace:"RxMVVM.xcworkspace",scheme:"RxMVVM")
cocoapods(
  clean_install: true
)
end

 # ------------ Archive file -------------
lane :release do
  # Providing the xcodeproj is optional
  increment_build_number(xcodeproj: "RxMVVM.xcodeproj")
  # Commit the version bump
  clean_build_artifacts
  commit_version_bump(xcodeproj: "RxMVVM.xcodeproj")
  # push_to_git_remote()
  gym(scheme: "RxMVVM",
        export_method: "ad-hoc")
end

 # ------------ upload fild to appcenter -------------
lane :deploy do
  appcenter_upload(
  api_token: "9de01f054ce092ef372fa63bc7aab84f9f0588e4",
  owner_name: "hoanguit",
  owner_type: "user", # Default is user - set to organization for appcenter organizations
  app_name: "RxSample",
  file: "./RxMVVM.ipa",
  notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
)
end

end
