# default_platform(:ios)
#
# platform :ios do
#
#
# end
# lane :beta do
#   build_app(
#     export_method: "app-store",
#     export_options: {
#       provisioningProfiles: {
#         "com.example.bundleid" => "Provisioning Profile Name",
#         "com.example.bundleid2" => "Provisioning Profile Name 2"
#       }
#     }
#   )
# end
default_platform(:ios)

platform :ios do
  desc "Test distribution "
lane :release do
  # Providing the xcodeproj is optional
  increment_build_number(xcodeproj: "RxMVVM.xcodeproj")
  # Commit the version bump
  clean_build_artifacts
  commit_version_bump(xcodeproj: "RxMVVM.xcodeproj")
  push_to_git_remote
  sync_code_signing
  enable_automatic_code_signing(path: "RxMVVM.xcodeproj")
  build_app(scheme: "RxMVVM")
  hockey(api_token: "[9de01f054ce092ef372fa63bc7aab84f9f0588e4]")

end
end
